codecov:
  require_ci_to_pass: true

coverage:
  precision: 2 # how many decimal places to display in the UI: 0 <= value <= 4
  round: nearest # how coverage is rounded: down/up/nearest
  range: 50...70 # custom range of coverage colors from red -> yellow -> green
  status:
    # pull-requests only
    patch:
      default:
        threshold: 3.0% # coverage can drop up top 3% without giving failure
    project:
      default:
        threshold: 3.0% # coverage can drop up top 3% without giving failure

# comment: false  # to disable comments
comment:
  layout: 'header, diff, changes, sunburst, suggestions, tree'
  behavior:
    new
    # option: "default" posts once then update, posts new if delete
    # option: "once"    post once then updates, if deleted do not post new
    # option: "new"     delete old, post new
    # option: "spammy"  post new
